In [2]:
import numpy as np

# Анализ данных с использованием библиотеки NumPy

## Создание массивов
1. Создайте одномерный массив из 10 случайных чисел.

2. Создайте двумерный массив размером 3x3, содержащий случайные числа.

3. Создайте массив с числами от 1 до 20 включительно с шагом 2.


In [6]:
np.random.sample(10)

array([0.26435453, 0.4025133 , 0.26977843, 0.94020432, 0.41697849,
       0.96894006, 0.58236479, 0.73531022, 0.26932456, 0.94685488])

In [149]:
# np.array([[1.5, 2, 3], [4, 5, 6]]) 
a=np.random.rand(3,3)
a


array([[0.90782985, 0.56929338, 0.77118085],
       [0.1380946 , 0.8876025 , 0.49353323],
       [0.27495801, 0.91995726, 0.88434164]])

In [50]:
np.arange(1,20,2)

np.arange(1,20,2)+1

   


array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])


## Информация о массиве
4. Выведите форму (размер) массива из задачи 2, используя атрибут `shape`.

5. Определите тип данных элементов массива из задачи 3, используя атрибут `dtype`.


In [150]:
a.shape

(3, 3)

In [153]:
np.arange(1,20,2).dtype

(np.arange(1,20,2)+1).dtype

dtype('int32')


## Операции с массивами
6. Умножьте каждый элемент массива из задачи 1 на 3.

7. Посчитайте сумму элементов массива из задачи 2 по каждой оси, используя функцию `np.sum()`.


In [314]:
a=np.random.sample(10)
print(a*3)

[1.30457043 1.82578759 1.63898844 0.05023955 0.70484427 1.81605209
 0.88919266 1.84935167 1.82581957 2.89621761]


In [328]:
a=np.random.rand(3,3).sum()
a


4.490967066195532


## Индексация и срезы
8. Получите элемент из середины массива из задачи 1.

9. Выделите подматрицу размером 2x2 из массива задачи 2.


In [340]:
np.random.sample(10)[4]

0.8102309810972235

In [426]:
a=np.random.rand(3,3)
a=a[:2,:2]
a

array([[0.20654182, 0.88547244],
       [0.02627232, 0.98985313]])


## Статистика и агрегация
10. Найдите среднее значение всех элементов массива из задачи 1, используя функцию `np.mean()`.

11. Найдите максимальное значение в каждой строке массива из задачи 2, используя функцию `np.max()`.


In [435]:
# np.random.sample(10).mean()
matr=np.random.sample(10)
np.mean(matr)



0.5455120468698055

In [20]:
np.random.rand(3,3).max()

0.9869504786418554


## Логические операции
12. Создайте логический массив, проверяющий, какие элементы массива из задачи 1 больше 5.

13. Получите только те элементы массива из задачи 3, которые делятся на 3 без остатка.


In [68]:
# a=np.random.sample(10)+11 
a = np.random.uniform(1, 10, 10)
print(a)
for i in a:
    if i > 5:
        # print(i)
        True


[9.18187403 9.28286131 1.47580014 9.13001178 4.50304952 1.76391234
 5.69941858 3.63499744 8.13575882 1.34347164]
9.181874030941712
9.282861311226938
9.130011775112871
5.69941858059112
8.135758815120305


In [113]:
a=np.arange(1,20,2)

# np.arange(1,20,2)+1

for i in a:
    if i % 3 == 0:
        print(i)
   


3
9
15



## Работа с формой массива
14. Преобразуйте одномерный массив из задачи 1 в двумерный массив размером 2x5, используя метод `reshape()`.

15. Транспонируйте массив из задачи 2, используя метод `T`.


In [111]:
np.random.sample(10).reshape(2,5)


array([[0.69686705, 0.11115488, 0.72444723, 0.48648232, 0.63787381],
       [0.86389008, 0.5265839 , 0.13567637, 0.94902998, 0.98926517]])

In [9]:
np.random.rand(3,3).T

array([[0.5417452 , 0.28753044, 0.20661129],
       [0.42192614, 0.85619782, 0.67144961],
       [0.04358441, 0.96445424, 0.10093276]])


## Сортировка и индексация
16. Отсортируйте элементы массива из задачи 1 по убыванию, используя функцию `np.sort()`.

17. Найдите индексы минимальных значений в каждом столбце массива из задачи 2, используя функцию `np.argmin()`.


In [154]:
a=np.random.sample(10)
a=np.sort(a)[::-1]
# arr = np.array([0, 100000000000000000000000000, 100000000000000000000000000, 100000000000000000000000000, 100000000000000000000000000, 100000000000000000000000000, 100000000000000000000000000,100000000000000000000000000, 100000000000000000000000000, 100000000000000000000000000])
# arr = np.sort(arr)[::-1]
a

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [211]:
a=np.random.rand(3,3)
a=np.argmin(a,axis=0)#столбец 
# a=np.argmin(a,axis=1) строка
print(a)

# a=np.argmin(a)
# a

[0 0 0]



## Уникальные значения
18. Найдите уникальные значения в массиве из задачи 1, используя функцию `np.unique()`.

19. Посчитайте количество повторяющихся элементов в массиве из задачи 3, используя функцию `np.bincount()`.


In [223]:
a=np.random.sample(10)
a=np.unique(a)
a

array([0.14818097, 0.28603739, 0.37347898, 0.39384888, 0.50005344,
       0.53249871, 0.70024439, 0.88240148, 0.91426502, 0.94663187])

In [233]:
a = np.arange(1,20,2)
a = (np.bincount(a))
count = 0
for i in a:
    if i > 1:
        count+=1
count



0


## Линейная алгебра
20. Выполните матричное умножение двух массивов размером 3x3 из задачи 2, используя функцию `np.dot()`.

21. Решите систему линейных уравнений: `2x + y = 8` и `3x - y = 1`, используя функцию `np.linalg.solve()`.


In [244]:
arr=np.random.rand(3,3)
# print(arr)
arr1=np.random.rand(3,3)
# print(arr1)
dot = np.dot(arr,arr1)
dot


array([[0.12162217, 0.3388185 , 1.56147361],
       [0.14959043, 0.56654042, 1.51838087],
       [0.14473802, 0.50246896, 1.51531752]])

In [295]:
arr = np.array([[2,1], [3,-1]])
arr1 = np.array([8,1])
x=np.linalg.solve(arr,arr1)
print(x[0],x[1])

1.8 4.4



## Векторизация
22. Создайте функцию, которая принимает на вход массив и возвращает новый массив, содержащий квадраты элементов входного массива.

23. Примените функцию из задачи 22 к массиву из задачи 1 с использованием векторизации.


In [309]:
arr1=np.array([100000000000000000000000000000000,100000000000000000000000000000000])
arr = np.square(arr1)
print(arr)
def Square(Array):
    return np.square(Array)
print((Square(arr1)))



[10000000000000000000000000000000000000000000000000000000000000000
 10000000000000000000000000000000000000000000000000000000000000000]
[10000000000000000000000000000000000000000000000000000000000000000
 10000000000000000000000000000000000000000000000000000000000000000]


In [315]:
a=np.random.rand(3,3)
vector = np.vectorize(Square(a))
vector




## Статистика
24. Посчитайте медиану элементов массива из задачи 1, используя функцию `np.median()`.

25. Найдите стандартное отклонение значений в каждой строке массива из задачи 2, используя функцию `np.std()`.

In [317]:
a=np.random.rand(3,3)
a=np.median(a)
a


0.340676562560587

In [320]:
a=np.random.rand(3,3)
np.std(a)

0.24733613847080718